import sharp from "sharp";
import fs from "fs";
import path from "path";

const ROOT_DIR = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(ROOT_DIR, "public");
const ICONS_DIR = path.join(PUBLIC_DIR, "imgs/agents/icons");
const PORTRAITS_DIR = path.join(PUBLIC_DIR, "imgs/agents/portraits");
const ROLES_DIR = path.join(PUBLIC_DIR, "imgs/roles");
const OUTPUT_DIR = path.join(PUBLIC_DIR, "imgs/agents");
const SPRITE_MAP_PATH = path.join(ROOT_DIR, "src/data/spriteMap.ts");

const COLUMNS = 10;

const agentKeys = fs
  .readdirSync(ICONS_DIR)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => f.replace(".webp", ""))
  .sort();

async function generateSprite(
  inputDir: string,
  outputPath: string,
  cellWidth: number,
  cellHeight: number,
) {
  const rows = Math.ceil(agentKeys.length / COLUMNS);
  const composites = agentKeys.map((key, i) => ({
    input: path.join(inputDir, `${key}.webp`),
    left: (i % COLUMNS) * cellWidth,
    top: Math.floor(i / COLUMNS) * cellHeight,
  }));

  await sharp({
    create: {
      width: COLUMNS * cellWidth,
      height: rows * cellHeight,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .webp({ quality: 85 })
    .toFile(outputPath);

  console.log(`Generated: ${outputPath}`);
}

const roleKeys = ["controller", "sentinel", "initiator", "duelist"];

async function generateRoleSprite() {
  const cellSize = 16;
  const columns = roleKeys.length;
  const composites = roleKeys.map((key, i) => ({
    input: path.join(ROLES_DIR, `${key}.webp`),
    left: i * cellSize,
    top: 0,
  }));

  const outputPath = path.join(PUBLIC_DIR, "imgs/roles/role-icons-sprite.webp");
  await sharp({
    create: {
      width: columns * cellSize,
      height: cellSize,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .webp({ quality: 85, lossless: true })
    .toFile(outputPath);

  console.log(`Generated: ${outputPath}`);
}

async function generateSpriteMap() {
  const totalRows = Math.ceil(agentKeys.length / COLUMNS);

  const positions = agentKeys
    .map((key, i) => {
      const col = i % COLUMNS;
      const row = Math.floor(i / COLUMNS);
      return `  ${key}: { col: ${col}, row: ${row} }`;
    })
    .join(",\n");

  const rolePositions = roleKeys
    .map((key, i) => `  ${key}: ${i}`)
    .join(",\n");

  const content = `// Auto-generated by scripts/generate-sprites.ts -- do not edit manually

export const ICON_SPRITE = {
  src: "/imgs/agents/agent-icons-sprite.webp",
  columns: ${COLUMNS},
  rows: ${totalRows},
} as const;

export const PORTRAIT_SPRITE = {
  src: "/imgs/agents/agent-portraits-sprite.webp",
  columns: ${COLUMNS},
  rows: ${totalRows},
} as const;

export const ROLE_SPRITE = {
  src: "/imgs/roles/role-icons-sprite.webp",
  columns: ${roleKeys.length},
} as const;

export const roleSpritePositions: Record<string, number> = {
${rolePositions},
};

export const spritePositions: Record<string, { col: number; row: number }> = {
${positions},
};
`;

  fs.writeFileSync(SPRITE_MAP_PATH, content);
  console.log(`Generated: ${SPRITE_MAP_PATH}`);
}

async function main() {
  await generateSprite(
    ICONS_DIR,
    path.join(OUTPUT_DIR, "agent-icons-sprite.webp"),
    80,
    80,
  );
  await generateSprite(
    PORTRAITS_DIR,
    path.join(OUTPUT_DIR, "agent-portraits-sprite.webp"),
    350,
    350,
  );
  await generateRoleSprite();
  await generateSpriteMap();

  console.log(`Done! ${agentKeys.length} agents processed.`);
}

main();
