// Auto-generated by scripts/generate-sprites.ts -- do not edit manually

export const ICON_SPRITE = {
  src: "/imgs/agents/agent-icons-sprite.webp",
  columns: 10,
  rows: 3,
} as const;

export const PORTRAIT_SPRITE = {
  src: "/imgs/agents/agent-portraits-sprite.webp",
  columns: 10,
  rows: 3,
} as const;

export const ROLE_SPRITE = {
  src: "/imgs/roles/role-icons-sprite.webp",
  columns: 4,
} as const;

export const roleSpritePositions: Record<string, number> = {
  controller: 0,
  sentinel: 1,
  initiator: 2,
  duelist: 3,
};

export const spritePositions: Record<string, { col: number; row: number }> = {
  astra: { col: 0, row: 0 },
  breach: { col: 1, row: 0 },
  brimstone: { col: 2, row: 0 },
  chamber: { col: 3, row: 0 },
  clove: { col: 4, row: 0 },
  cypher: { col: 5, row: 0 },
  deadlock: { col: 6, row: 0 },
  fade: { col: 7, row: 0 },
  gekko: { col: 8, row: 0 },
  harbor: { col: 9, row: 0 },
  iso: { col: 0, row: 1 },
  jett: { col: 1, row: 1 },
  kayo: { col: 2, row: 1 },
  killjoy: { col: 3, row: 1 },
  miks: { col: 4, row: 1 },
  neon: { col: 5, row: 1 },
  omen: { col: 6, row: 1 },
  phoenix: { col: 7, row: 1 },
  raze: { col: 8, row: 1 },
  reyna: { col: 9, row: 1 },
  sage: { col: 0, row: 2 },
  skye: { col: 1, row: 2 },
  sova: { col: 2, row: 2 },
  tejo: { col: 3, row: 2 },
  veto: { col: 4, row: 2 },
  viper: { col: 5, row: 2 },
  vyse: { col: 6, row: 2 },
  waylay: { col: 7, row: 2 },
  yoru: { col: 8, row: 2 },
};
